"""remove_is_public_from_collections

Revision ID: 87608840a4d4
Revises: ddf20b03074f
Create Date: 2025-06-26 00:07:20.906781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87608840a4d4'
down_revision: Union[str, None] = 'ddf20b03074f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
