"""auto migration

Revision ID: e336498d9d4b
Revises: 775054ade9fc
Create Date: 2025-06-30 02:45:46.715954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e336498d9d4b'
down_revision: Union[str, None] = '775054ade9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dealers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealers'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_transactions_dealer_id_dealers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.add_column('items', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('price', sa.Float(), nullable=True))
    op.create_foreign_key(op.f('fk_items_transaction_id_transactions'), 'items', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_transaction_id_transactions'), 'items', type_='foreignkey')
    op.drop_column('items', 'price')
    op.drop_column('items', 'transaction_id')
    op.drop_table('transactions')
    op.drop_table('dealers')
    # ### end Alembic commands ###
