"""change_datetime_to_date_in_price_history

Revision ID: 1e2bfadde31d
Revises: 07801d5eefc5
Create Date: 2025-07-17 00:01:45.771320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1e2bfadde31d"
down_revision: Union[str, None] = "07801d5eefc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_price_history",
        sa.Column(
            "date", sa.Date(), nullable=False, server_default=sa.func.current_date()
        ),
    )
    op.drop_column("item_price_history", "datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_price_history",
        sa.Column(
            "datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("item_price_history", "date")
    # ### end Alembic commands ###
