"""add_grading_tables

Revision ID: 64214493be12
Revises: f70e35c4c3aa
Create Date: 2025-09-01 01:46:10.469621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64214493be12'
down_revision: Union[str, None] = 'f70e35c4c3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_companies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('cert_url_pattern', sa.Text(), nullable=True),
    sa.Column('supported_types', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_grading_companies_name')),
    sa.UniqueConstraint('short_name', name=op.f('uq_grading_companies_short_name'))
    )
    op.create_table('grades',
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Grading system: modern, ancient, details'),
    sa.Column('value', sa.String(length=50), nullable=False, comment='Grade value (MS 70, Ch XF, CLEANED, etc.)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order within category'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grades_company_id_grading_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades'))
    )
    op.create_table('grading_info',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('certificate_number', sa.String(length=255), nullable=False, comment='Unique certificate number from grading company'),
    sa.Column('grade', sa.String(length=50), nullable=True, comment='Assigned grade (e.g., MS70, AU58)'),
    sa.Column('grade_details', sa.String(length=100), nullable=True, comment='Additional grade details (e.g., CLEANED, DAMAGED)'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='Additional notes about the grading'),
    sa.Column('certificate_url', sa.Text(), nullable=True, comment='URL to verify certificate online'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grading_info_company_id_grading_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_grading_info_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_info')),
    sa.UniqueConstraint('item_id', name='uq_grading_info_item_id')
    )
    op.create_index(op.f('ix_grading_info_company_id'), 'grading_info', ['company_id'], unique=False)
    op.create_index(op.f('ix_grading_info_item_id'), 'grading_info', ['item_id'], unique=False)
    op.alter_column('item_images', 'type',
               existing_type=postgresql.ENUM('FRONT', 'BACK', 'ADDITIONAL', name='imagetype'),
               comment='Type of the image (e.g., front, back)',
               existing_comment='Type of the image (e.g., FRONT, BACK)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_images', 'type',
               existing_type=postgresql.ENUM('FRONT', 'BACK', 'ADDITIONAL', name='imagetype'),
               comment='Type of the image (e.g., FRONT, BACK)',
               existing_comment='Type of the image (e.g., front, back)',
               existing_nullable=False)
    op.drop_index(op.f('ix_grading_info_item_id'), table_name='grading_info')
    op.drop_index(op.f('ix_grading_info_company_id'), table_name='grading_info')
    op.drop_table('grading_info')
    op.drop_table('grades')
    op.drop_table('grading_companies')
    # ### end Alembic commands ###
