"""add_parent_id_to_collections

Revision ID: 367bf42efaa8
Revises: db66a58e87c5
Create Date: 2025-09-06 19:02:34.361156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367bf42efaa8'
down_revision: Union[str, None] = 'db66a58e87c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_collections_parent_id'), 'collections', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_collections_parent_id_collections'), 'collections', 'collections', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_collections_parent_id_collections'), 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_parent_id'), table_name='collections')
    op.drop_column('collections', 'parent_id')
    # ### end Alembic commands ###
