"""init

Revision ID: f70e35c4c3aa
Revises: 
Create Date: 2025-07-24 18:05:08.343079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70e35c4c3aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('access_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_tokens_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_access_tokens'))
    )
    op.create_index(op.f('ix_access_tokens_created_at'), 'access_tokens', ['created_at'], unique=False)
    op.create_table('collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('share_token', name=op.f('uq_collections_share_token'))
    )
    op.create_table('counterparties',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SELLER', 'BUYER', 'BOTH', name='counterpartyrole'), nullable=False, server_default='BOTH'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_counterparties_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties'))
    )
    op.create_table('items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material', sa.Enum('GOLD', 'SILVER', 'COPPER', 'BRONZE', 'NICKEL', 'ALUMINUM', 'BRASS', 'PLATINUM', 'STEEL', 'ZINC', 'TIN', 'LEAD', name='material'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_items_collection_id_collections')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_items_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_table('item_images',
    sa.Column('type', sa.Enum('FRONT', 'BACK', 'ADDITIONAL', name='imagetype'), nullable=False, comment='Type of the image (e.g., FRONT, BACK)'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='Storage path (S3 key or local path)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME type (e.g., image/jpeg)'),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_images_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_images'))
    )
    op.create_index('idx_unique_front_back_per_item', 'item_images', ['item_id', 'type'], unique=True, postgresql_where="type IN ('FRONT', 'BACK')")
    op.create_index(op.f('ix_item_images_type'), 'item_images', ['type'], unique=False)
    op.create_table('item_price_history',
    sa.Column('price', sa.BigInteger(), nullable=False, comment='Price in pennies/cents'),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE', 'CURRENT', name='pricetype'), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_price_history_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_price_history'))
    )
    op.create_index(op.f('ix_item_price_history_item_id'), 'item_price_history', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_price_history_type'), 'item_price_history', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_price_history_type'), table_name='item_price_history')
    op.drop_index(op.f('ix_item_price_history_item_id'), table_name='item_price_history')
    op.drop_table('item_price_history')
    op.drop_index(op.f('ix_item_images_type'), table_name='item_images')
    op.drop_index('idx_unique_front_back_per_item', table_name='item_images', postgresql_where="type IN ('FRONT', 'BACK')")
    op.drop_table('item_images')
    op.drop_table('items')
    op.drop_table('counterparties')
    op.drop_table('collections')
    op.drop_index(op.f('ix_access_tokens_created_at'), table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # Drop custom enum types
    op.execute('DROP TYPE IF EXISTS counterpartyrole')
    op.execute('DROP TYPE IF EXISTS pricetype')
    op.execute('DROP TYPE IF EXISTS imagetype')
    op.execute('DROP TYPE IF EXISTS material')
    # ### end Alembic commands ###
