"""change_item_collection_relation_to_one_to_many

Revision ID: 4caebb7ee26f
Revises: 87608840a4d4
Create Date: 2025-06-30 15:50:37.505915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caebb7ee26f'
down_revision: Union[str, None] = '87608840a4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_items')
    op.add_column('items', sa.Column('collection_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(op.f('fk_items_collection_id_collections'), 'items', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_collection_id_collections'), 'items', type_='foreignkey')
    op.drop_column('items', 'collection_id')
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_collection_items_item_id_items')),
    sa.PrimaryKeyConstraint('collection_id', 'item_id', name=op.f('pk_collection_items'))
    )
    # ### end Alembic commands ###
