"""add_transaction_item_model

Revision ID: bc45f5e24e74
Revises: c0dec4e9b488
Create Date: 2025-09-04 21:11:45.383813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc45f5e24e74'
down_revision: Union[str, None] = 'c0dec4e9b488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ensure currency enum exists (safe to run multiple times)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'currency') THEN
                CREATE TYPE currency AS ENUM ('USD', 'EUR');
            END IF;
        END
        $$;
    """)
    
    op.create_table('transaction_items',
    sa.Column('price', sa.BigInteger(), nullable=False, comment='Item price in this transaction (pennies/cents)'),
    sa.Column('currency', sa.Enum('USD', 'EUR', name='currency', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_transaction_items_item_id_items')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_items_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_items'))
    )
    op.create_index(op.f('ix_transaction_items_item_id'), 'transaction_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_item_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    # ### end Alembic commands ###
