"""add_price_history

Revision ID: 07801d5eefc5
Revises: 4caebb7ee26f
Create Date: 2025-07-12 23:23:45.455372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07801d5eefc5"
down_revision: Union[str, None] = "4caebb7ee26f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dealers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dealers_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dealers")),
    )
    op.create_table(
        "item_price_history",
        sa.Column(
            "price", sa.BigInteger(), nullable=False, comment="Price in pennies/cents"
        ),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PURCHASE", "SOLD", "CURRENT", name="pricetype"),
            nullable=False,
        ),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_price_history_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_price_history")),
    )
    op.create_index(
        op.f("ix_item_price_history_item_id"),
        "item_price_history",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_price_history_type"), "item_price_history", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_price_history_type"), table_name="item_price_history")
    op.drop_index(
        op.f("ix_item_price_history_item_id"), table_name="item_price_history"
    )
    op.drop_table("item_price_history")
    op.drop_table("dealers")

    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS pricetype")
    # ### end Alembic commands ###
