"""add_transaction_collection_model

Revision ID: 29b8555ee347
Revises: 367bf42efaa8
Create Date: 2025-09-06 21:45:51.892181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b8555ee347'
down_revision: Union[str, None] = '367bf42efaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First create table without currency column
    op.create_table('transaction_collections',
    sa.Column('transaction_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('collection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_transaction_collections_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_collections_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_collections'))
    )
    
    # Add currency column separately using existing enum
    op.add_column('transaction_collections', sa.Column('currency', sa.Enum('USD', 'EUR', name='currency', create_type=False), nullable=False))
    
    op.create_index(op.f('ix_transaction_collections_collection_id'), 'transaction_collections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_transaction_collections_transaction_id'), 'transaction_collections', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_transactions_collection_id'), table_name='transactions')
    op.drop_constraint(op.f('fk_transactions_collection_id_collections'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_transactions_collection_id_collections'), 'transactions', 'collections', ['collection_id'], ['id'])
    op.create_index(op.f('ix_transactions_collection_id'), 'transactions', ['collection_id'], unique=False)
    op.drop_index(op.f('ix_transaction_collections_transaction_id'), table_name='transaction_collections')
    op.drop_index(op.f('ix_transaction_collections_collection_id'), table_name='transaction_collections')
    op.drop_table('transaction_collections')
    # ### end Alembic commands ###
